services:
  app:
    build:
      dockerfile: ./docker/php-fpm/Dockerfile
    container_name: laravel-app
    working_dir: /var/www/
    volumes:
      - ./my-app:/var/www/
    networks:
      - laravel

  nginx:
    image: nginx:stable-alpine
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - ./my-app:/var/www/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  mysql_data:
